### ISSUE TITLE
Activity spelled wrong

### ISSUE THREAD

**Issue by dougroutledge** [kenakamu/UCWA2.0-CS#1]
In the Presence.cs file, the line [JsonProperty("activity")] is spelled wrong.

**Comment by kenakamu** [comment]
Thanks! fixed.

**Comment by dougroutledge** [comment]
Even when changing on my end, it still doesn’t seem to set the activity.

 

public class Presence : UCWAModelBaseLink

    {

        [JsonProperty("activity")]

        public string Activity { get; set; }

 

        [JsonProperty("availability")]

        public Availability Availability { get; set; }

 

        public async Task Update()

        {

            await HttpService.Post(Self, this);

        }

    }

 

 

I can trace and see it is sending this.

 

{

  "activity": "In a Call",

  "availability": "Busy",

  "Self": "/ucwa/oauth/v1/applications/103782700393/me/presence",

  "rel": "presence"

}

 

But when I query the presence, the activity portion is always null.

 

presence = (await Globlas.client.Me.GetPresencs());

 

The Availability seems to change properly.

**Comment by kenakamu** [comment]
Interesting. Can you check if UCWA returns activity when run presence method?

**Comment by dougroutledge** [comment]
Yes I can read if I am in a meeting or on the phone, but I am not able to set.  It could be that it is not supported.  I see this link talks about well known tokens and custom tokens, and says custom tokens can’t be set.  I don’t seem to be able to set the well know tokens either.

 

https://ucwa.skype.com/documentation/Dashboard-Me

**Comment by kenakamu** [comment]
You are right. It seems they are not (yet) supported setting it.
