### ISSUE TITLE
How to send Image as IM

### ISSUE THREAD

**Issue by harigovind2102** [kenakamu/UCWA2.0-CS#14]
hey i am using user project as base for one of my application , i was wondering how to send image as a part of IM, i was able to achieve the same with Lync SDK where i set the "InstantMessageContentType.Gif" and pass in the base 64 string for the image. I am assuming that is what we should do here as well but i was unable to find the option to do so.

**Comment by kenakamu** [comment]
Good question. Let me try to figure it out and back to you. Please wait.

**Comment by harigovind2102** [comment]
yap i'll be trying it at my end too....
thanks anyway

**Comment by kenakamu** [comment]
cannot figure it out yet... I will ask my team today.

**Comment by kenakamu** [comment]
At the end, it seems we cannot send/receive attachment via UCWA 2.0. Only plain and html text.

**Comment by dipincluster** [comment]
hey @kenakamu  I am using UCWA 2.0 for one of my implementation , i am trying to send image ....i believe it can be done as Skype for Business client which enables users to send images, i was experimenting with sending base64 image using Text/html type but it was not rendered can you tell me what should be the payload in the body of the post to 
"**POST https://lync.contoso.com/ucwa/oauth/v1/applications/102/communication/conversations/21a1/messaging**"I have attached a image which does this post request...this is your implementation only ...previously i was able to send html content by changing the content type for the Body

**Comment by kenakamu** [comment]
Do you have a code which could send images before? Or did you resolve this by setting correct content type?

**Comment by dipincluster** [comment]
no , i don't have any code which sends images, but i am trying to resolve this issue of sending images...I was hoping you would know the correct content type
