### ISSUE TITLE
UCWA on Premise

### ISSUE THREAD

**Issue by 86simonepenna** [kenakamu/UCWA2.0-CS#15]
Hello,

With Skype on Line is OK!

How to use this SDK for Skype Business On Server (on premise)?

I have not the tenant on my server.

Thank You

**Comment by kenakamu** [comment]
I should be same but only authentication part is slightly different. Please follow the steps here to register app.
https://msdn.microsoft.com/en-us/skype/ucwa/developingucwaapplicationsforskypeforbusinessserver

**Comment by kenakamu** [comment]
added sample
