### ISSUE TITLE
Client Secret required

### ISSUE THREAD

**Issue by AuriR** [kenakamu/UCWA2.0-CS#17]
I'm receiving an error when attempting to authentication that the Client Secret was not passed. Where do I pass that using the test client, please? Maybe I'm missing something obvious? :)

Thanks! Tried reaching out on Twitter, etc. but GitHub doesn't show your contact info. I'm @Auri on Twitter

**Comment by AuriR** [comment]
A little more detail on the error. In the test client in TokenService.cs when calling AquireAADToken on Line 34, I get the following error:

{"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: 71ff5302-c167-44a4-88cc-490e20a40000\r\nCorrelation ID: e7e29376-a6bd-4cd3-b26f-37976a037338\r\nTimestamp: 2017-04-14 19:54:52Z"}

**Comment by AuriR** [comment]
Ahh, I see what's going on. I needed to create a Native Application, not a Web Application. Now I need to figure out how to create the application with the Graph API or PowerShell.

**Comment by kenakamu** [comment]
I believe you can do so with web application. PowerShell one is tricky as we need to figure out how to wait call back. To get adal token Check out my repository which has PowerShell module to do so

**Comment by AuriR** [comment]
Thank you, Nakamura-san! I'll take a look at the script.
