### ISSUE TITLE
Add PanoramicVideo to Microsoft.Skype.UCWA.Enums.ConversationModalityType

### ISSUE THREAD

**Issue by elav000** [kenakamu/UCWA2.0-CS#32]
I believe that the 'PanoramicVideo' value is missing from this enum. I attempted to get a conversation for a meeting I had joined and received this error:
Error converting value "PanoramicVideo" to type 'Microsoft.Skype.UCWA.Enums.ConversationModalityType'. Path 'sender[0].events[1]._embedded.conversation.activeModalities[2]', line 59, position 32.

**Comment by kenakamu** [comment]
Indeed. Thanks for the report.
