### ISSUE TITLE
Continuous publishing/release of the SDK to nuget

### ISSUE THREAD

**Issue by baywet** [kenakamu/UCWA2.0-CS#43]
Hey @kenakamu other follow up of #39 
Currently we don't have any automated publishing of the package. This one is dependant of #42 
I could get us up to speed fairly fast on VSTS but it brings the same concerns.
Also the technology should provide us pre-deployment approval capabilities to avoid all merges to master going straight to nuget.

**Comment by kenakamu** [comment]
Yes good idea. I will add you as co-owner of the project on NuGet.org. please let me know your nuget account.

**Comment by baywet** [comment]
Same as GitHub email vincentbiret@hotmail.com

**Comment by kenakamu** [comment]
please verify you are added/

**Comment by baywet** [comment]
Seems to have worked, thanks!
