### ISSUE TITLE
How to send HTML formatted messages?

### ISSUE THREAD

**Issue by buchizo** [kenakamu/UCWA2.0-CS#47]
This SDK support html formatted message. However I guess this SDK send message using plain format, always. 

see also this issue #26 , but that issue is closed. ( doesn't fix?)

I want to support html formatted message in some method (e.g. Send/ReplyMessage)

**Comment by baywet** [comment]
Hey @buchizo it looks like your issue is a duplicate of https://github.com/kenakamu/UCWA2.0-CS/issues/21 or a least related, can you confirm?

**Comment by buchizo** [comment]
@baywet Thank you for your information. I'll close this because this issue is duplicated.
