### ISSUE TITLE
On Premise Option

### ISSUE THREAD

**Issue by delta1186** [kenakamu/UCWA2.0-CS#49]
Is it possible to port this to work for on premise implementations of SfB?

**Comment by baywet** [comment]
Hi @delta1186 thanks for reaching out.
Besides the fact that we don't have any Skype For Business farm to test the library against the on prémices version, it should work as is (the protocol being the same as far as I know).
Please go ahead and try it out, and open issues/submit PRs for things that don't work

**Comment by lazaromenezes** [comment]
Sorry commenting on this closed issue, but yes, it does work with an on premise environment. We have been using it for a while with this setup.
