### ISSUE TITLE
Unable to get reply from other user.

### ISSUE THREAD

**Issue by ankitabhishek93** [kenakamu/UCWA2.0-CS#5]
Hi,
I am unable to get the response from the user on skype UI as it only shows on the console.
How to get it On the skype UI.

 private void Client_MessageReceived(Message message)
        {
            ConsoleWrite_Green("Messaged Received from {0}: {1}", message.GetParticipant().Result.Uri, message.Text);
            //client.ReplyMessage(message.Text, message).Wait();
        }

Above code only print my message on the console but i need to show it on my Skype for Business UI .

**Comment by kenakamu** [comment]
You can consider UCWA as separate instance of Skype for Business. It is not SfB client add-on. So what you do on console app may not reflect on SfB client all the time.
