### ISSUE TITLE
How to remove a participant from an online meeting

### ISSUE THREAD

**Issue by payneauj** [kenakamu/UCWA2.0-CS#50]
Hello, 

I would like to if it is possible to remove a participant from an online meeting?

I have an online meeting between 3 persons. The first one use the skype web control, the second one use your SDK in an UWP app and the last one use the skype mobile app. 

I want to be able to remove the participant that use the smartphone skype application. 

Is it possible? I try to get the participant and call eject or reject but it does not fire ParticipantDeleted event. 

Thanks for your help 

Jocelyn

**Comment by baywet** [comment]
According to [the documentation](https://msdn.microsoft.com/en-us/skype/ucwa/eject_ref) it should remove the person from the conversation.
If you look at the http calls, are you getting any error? Any trace you could provide?

**Comment by kenakamu** [comment]
close for now with no update
