### ISSUE TITLE
How to replicate an instance of console application?

### ISSUE THREAD

**Issue by ankitabhishek93** [kenakamu/UCWA2.0-CS#6]
Hi,
I am having an issue with the replication of a console app instance as in console app i have integrated some api and i am getting a respond from the server and it is getting replicated to my console application but i am unbale to see it on my SFB UI so how to replicate that instance of a console application to SFB UI.

**Comment by kenakamu** [comment]
the console app and SfB are totally separate application, and we do not have control to replicate them.

**Comment by ankitabhishek93** [comment]
Thanx for the help!!!
