### ISSUE TITLE
conversationn issue

### ISSUE THREAD

**Issue by ankitabhishek93** [kenakamu/UCWA2.0-CS#7]
Hi,
As i am trying to add contacts or change the availablitity of my sfb account through console app it replicates on sfb UI too but when i am trying to strat a conversation that dosen't come to UI at all no trace of conversation,It just happening on the console app.Need help in this, Why So??

**Comment by kenakamu** [comment]
That is because contacts and availability are server level status that any clients reflects the current data. However, chat is more like transaction so if one client get message, it will be lost from server. If two clients try to get message at same time it may be getting same data though

**Comment by ankitabhishek93** [comment]
Ohhh !!! thank you for the information.

**Comment by ankitabhishek93** [comment]
Hi, Any idea how this works https://www.officevibe.com/slack#top

**Comment by kenakamu** [comment]
Not sure about intention of the question but it is a slack bot:) looks nice
