### ISSUE TITLE
New UWP sample requires/uses login box

### ISSUE THREAD

**Issue by mjbedford2017** [kenakamu/UCWA2.0-CS#9]
Hello, 

Received the UWP sample, thank you very much. However, I noticed that with this sample, which does seem to work, when AquireAADToken method is called, a popup windows is launched asking user to supply the credentials. We want to store the username in password in the Token class (as you do have string fields to do so) and have login happen automatically instead of popping up a window.

How can this be done?

Thanks!

**Comment by kenakamu** [comment]
Once you login You don't need to sign in again but you need at least login once

**Comment by mjbedford2017** [comment]
Oh no, that is not desirable. Is there no way to have it log in for you? I have an app that will be running on Windows 10 Mobile. From my app, I want to send notifications via Skype For Business if the user selects to receive notifications in this way. I don't want to have to have them get a popup window on mobile, over my app and have to log in. 

With the code I pasted yesterday, I am able to get a string token without having a login box popup. Is there a way to implement or integrate that code so that no login is necessary?

Thanks!

**Comment by mjbedford2017** [comment]
And would that be one login per instance of the app running? Meaning, if I close the app, I need to do it again when I launch the app again?

**Comment by kenakamu** [comment]
Personally I don't know how to but if you embed cred, then all app login as same user which is not good scenario for SfB. Does your app integrate with azure as? Then you don't have to sign in separately. Login is not instance level so you can keep calling acquire token which won't ask you to login again as long as refresh token is valid

**Comment by mjbedford2017** [comment]
Yes, the organization uses Azure AD. I followed the instructions on your readme to register the application with Azure AD.

**Comment by mjbedford2017** [comment]
Even though I followed your instructions to register with Azure AD, there is some confusion over the Redirect URI. The instructions say I can use any URI and it doesn't matter but the login box that pops up fails when I try to login. At the bottom of the login box, it states there is an issue with the redirect URI. So, it seems the Redirect actually is important and while I have the setting on Azure AD matching the settings in the TokenService, it seems it does not like it.

Also, to note, I found that the sample application you mentioned and credited, from Tam Huynh, seems to work pretty well but it is much different than yours (console, non UWP application, can't send chats or view contacts, etc...) which is why your all inclusive library is more desirable. What is different about the way he gathers the tokens and everything versus your method? His does not ask for a popup box to login.

**Comment by kenakamu** [comment]
Okay, there are several things i need to let you know. RedirectUrl is actually important for UWP app, or any app need popup to signin. Which means it is not important for console app which i embed credential. I will update the note.

The reason why i put Tam's name is because I started the project by looking at his and we talked several time to decide what is good direction to write library.

So for your question, Redirect Uri is important and need to match with app. 

Good new is that if you already have application registered to Azure AD with your app, you dont need separate clientid. You just need to add SfB privilege delegates and re-use the same client id. Then if user login to your app (to Azure AD), it won't ask user to login again to same Azure AD account.

**Comment by mjbedford2017** [comment]
Hello again, and thank you so much for being so responsive and answering questions to help people (or me) understand better. Just a few follow up comments or questions.

1. So now I understand that RedirecUrl is important. It is only a requirement that they must match or must they also be a valid url or can they just be made up and not valid as long as they match?
2. I don't understand, if the console app can work with embedded credentials (and therefore not require a popup) why can I do the same in the library you have here? Or, what if I don't use it as a library but actually paste some of the code in my app? I don't understand how it can work on console but not anywhere else?
3. The organization uses Azure AD so I was able to login to our Azure AD to follow your steps to register this UCWP Skype library (and get tenant ID, client ID, etc...) BUT the devices which are going to be running the app, library and skype don't necessarily log in to Azure AD. I don't know if that even matters but I just wanted to clarify that. 

So, aside from the RedirectUrl question (if it has to be a valid Url or simply just match) which is only needed for the library when the login popup box is used, I also really want to know what is different with the console app? It almost feel like we can take the code from the console app that does the embedded credentials, login, getting tokens, etc... and put that in the library and everything will work the way some people want it, with embedded credentials.

Thanks again!!!

**Comment by kenakamu** [comment]
1. Redirect URL has to match with what you specify in your app but doesn't have to be valid DNS name. I usually use http://localhost/app

2. The authentication is not part of the library but depending on your own code. I strongly recommend using adal. The reason why it doesn't support embed cred should be policy which I don't have control.

3. It depends on your scenario but if you use Skype for business online, it infers users are on Azure AD, or federated to local AD via ADFS.

I've seen that UCWA support anonymous scenario as well though but it should be you starting the conversation and cannot simply receive message I guess.

The difference between console and native app authentication came from adal part. If Adal or platform let us embed credential, it would but I don't find a way yet

**Comment by kenakamu** [comment]
As no reply, I am closing this for now :)
